name: Windows Cygwin Test

on:
  workflow_dispatch:
  push:
    branches: cygwin

jobs:
  build_wheels_windows:
    runs-on: windows-latest
    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: git cmake gcc-g++ gcc-fortran python39-pip python39-devel openblas-devel meson

      - name: Check git and python
        run: |
          which git
          which python
          python --version
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      
      - name: Pull Espresso source
        run: |
          git clone https://github.com/inlab-geo/espresso.git
          ls
          cd espresso
          git describe
          pwd
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      
      - name: Get tags
        run: |
          cd espresso
          git fetch --tags origin
          git describe
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      
      - name: Prepare Python environment
        run: |
          cd espresso
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      
      - name: Generate package source with contributions
        run: |
          cd espresso
          python espresso_machine/build_package/build.py
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
