name: Windows Cygwin Test

on:
  workflow_dispatch:
  push:
    branches: cygwin

jobs:
  build_wheels_windows:
    runs-on: windows-latest
    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: git cmake gcc-g++ gcc-fortran python39-pip python39-devel meson

      - name: Check git and python
        run: |
          which git
          which python
          python --version
        shell: C:\cygwin\bin\bash.exe '{0}'
      
      - name: Pull Espresso source
        run: |
          git clone https://github.com/inlab-geo/espresso.git
        shell: C:\cygwin\bin\bash.exe '{0}'
      
      - name: Get tags
        working-directory: espresso
        run: |
          git fetch --tags origin
          git describe
        shell: C:\cygwin\bin\bash.exe '{0}'
      
      - name: Prepare Python environment
        working-directory: espresso
        run: |
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .
        shell: C:\cygwin\bin\bash.exe '{0}'
      
      - name: Generate package source with contributions
        working-directory: espresso
        run: |
          python espresso_machine/build_package/build.py
        shell: C:\cygwin\bin\bash.exe '{0}'
